apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-dep
  name: payments-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-dep
    spec:
      containers:
      - image: docker.io/library/tomee--port=8080
        name: tomee--port=8080
        resources: {}
status: {}
