apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: carts-dep
  name: carts-dep
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: carts-dep
  type: LoadBalancer
